"""Add plugin-owned storage tables

Revision ID: ddebea2fe0a8
Revises: 005
Create Date: 2026-03-07 00:53:41.458979

"""

from __future__ import annotations

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "ddebea2fe0a8"
down_revision = "005"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ccloud_billing",
        sa.Column("ecosystem", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("env_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("resource_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("product_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("product_category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("quantity", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("unit_price", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("total_cost", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("granularity", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("allocation_attempts", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("metadata_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint(
            "ecosystem", "tenant_id", "timestamp", "env_id", "resource_id", "product_type", "product_category"
        ),
    )

    # Migrate existing CCloud billing data from `billing` to `ccloud_billing`.
    # Extract env_id from metadata_json if present, otherwise use empty string.
    conn = op.get_bind()
    env_id_expr = (
        "COALESCE(metadata_json::json ->> 'env_id', '')"
        if conn.dialect.name == "postgresql"
        else "COALESCE(json_extract(metadata_json, '$.env_id'), '')"
    )
    conn.execute(
        sa.text(f"""
        INSERT INTO ccloud_billing (
            ecosystem, tenant_id, timestamp, env_id, resource_id,
            product_type, product_category, quantity, unit_price,
            total_cost, currency, granularity, allocation_attempts, metadata_json
        )
        SELECT
            ecosystem, tenant_id, timestamp,
            {env_id_expr} AS env_id,
            resource_id, product_type, product_category, quantity, unit_price,
            total_cost, currency, granularity, allocation_attempts, metadata_json
        FROM billing
        WHERE ecosystem = 'confluent_cloud'
    """)
    )

    # Delete migrated CCloud rows from the old billing table
    conn.execute(
        sa.text("""
        DELETE FROM billing WHERE ecosystem = 'confluent_cloud'
    """)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Move CCloud billing data back to core billing table
    conn = op.get_bind()
    if conn.dialect.name == "postgresql":
        env_id_collapse = conn.execute(
            sa.text("""
                SELECT 1
                FROM ccloud_billing
                GROUP BY ecosystem, tenant_id, timestamp, resource_id, product_type, product_category
                HAVING COUNT(*) > 1
                LIMIT 1
            """)
        ).first()
        if env_id_collapse is not None:
            raise RuntimeError(
                "migration ddebea2fe0a8 downgrade cannot merge ccloud_billing rows into billing "
                "because rows differ only by env_id; downgrade aborted before data changes"
            )

        target_collision = conn.execute(
            sa.text("""
                SELECT 1
                FROM ccloud_billing AS source
                JOIN billing AS target
                  ON target.ecosystem = source.ecosystem
                 AND target.tenant_id = source.tenant_id
                 AND target.timestamp = source.timestamp
                 AND target.resource_id = source.resource_id
                 AND target.product_type = source.product_type
                 AND target.product_category = source.product_category
                LIMIT 1
            """)
        ).first()
        if target_collision is not None:
            raise RuntimeError(
                "migration ddebea2fe0a8 downgrade cannot copy ccloud_billing rows into billing "
                "because target billing keys already exist; downgrade aborted before data changes"
            )

    conn.execute(
        sa.text("""
        INSERT INTO billing (
            ecosystem, tenant_id, timestamp, resource_id,
            product_type, product_category, quantity, unit_price,
            total_cost, currency, granularity, allocation_attempts, metadata_json
        )
        SELECT
            ecosystem, tenant_id, timestamp, resource_id,
            product_type, product_category, quantity, unit_price,
            total_cost, currency, granularity, allocation_attempts, metadata_json
        FROM ccloud_billing
    """)
    )
    op.drop_table("ccloud_billing")
    # ### end Alembic commands ###
