"""Add plugin-owned storage tables

Revision ID: ddebea2fe0a8
Revises: 005
Create Date: 2026-03-07 00:53:41.458979

"""

from __future__ import annotations

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "ddebea2fe0a8"
down_revision = "005"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ccloud_billing",
        sa.Column("ecosystem", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("env_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("resource_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("product_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("product_category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("quantity", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("unit_price", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("total_cost", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("currency", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("granularity", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("allocation_attempts", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("metadata_json", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint(
            "ecosystem", "tenant_id", "timestamp", "env_id", "resource_id", "product_type", "product_category"
        ),
    )

    # Migrate existing CCloud billing data from `billing` to `ccloud_billing`.
    # Extract env_id from metadata_json if present, otherwise use empty string.
    conn = op.get_bind()
    conn.execute(
        sa.text("""
        INSERT INTO ccloud_billing (
            ecosystem, tenant_id, timestamp, env_id, resource_id,
            product_type, product_category, quantity, unit_price,
            total_cost, currency, granularity, allocation_attempts, metadata_json
        )
        SELECT
            ecosystem, tenant_id, timestamp,
            COALESCE(json_extract(metadata_json, '$.env_id'), '') AS env_id,
            resource_id, product_type, product_category, quantity, unit_price,
            total_cost, currency, granularity, allocation_attempts, metadata_json
        FROM billing
        WHERE ecosystem = 'confluent_cloud'
    """)
    )

    # Delete migrated CCloud rows from the old billing table
    conn.execute(
        sa.text("""
        DELETE FROM billing WHERE ecosystem = 'confluent_cloud'
    """)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Move CCloud billing data back to core billing table
    conn = op.get_bind()
    conn.execute(
        sa.text("""
        INSERT INTO billing (
            ecosystem, tenant_id, timestamp, resource_id,
            product_type, product_category, quantity, unit_price,
            total_cost, currency, granularity, allocation_attempts, metadata_json
        )
        SELECT
            ecosystem, tenant_id, timestamp, resource_id,
            product_type, product_category, quantity, unit_price,
            total_cost, currency, granularity, allocation_attempts, metadata_json
        FROM ccloud_billing
    """)
    )
    op.drop_table("ccloud_billing")
    # ### end Alembic commands ###
